### ISSUE TITLE
gmail.com - broken

### ISSUE THREAD

**Issue by hawkeye116477** [elypter/BlockHead#1]
![screenshot_20180106_103559](https://user-images.githubusercontent.com/19818572/34638524-6c055ecc-f2cd-11e7-98db-b6b906a37259.png)

**Comment by elypter** [comment]
it looks ok for me in version 16 which i just uploaded. maybe i fixed it earlier and just forgot to push it to github. please tell me if it's different with v16

**Comment by elypter** [comment]
assuming it is now solved
